services:
  - type: web
    name: baynex-backend
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DERIV_API_TOKEN
        value: your_token_here
      - key: TELEGRAM_BOT_TOKEN
        value: your_token_here

  - type: web
    name: baynex-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port 3000
    envVars:
      - key: VITE_FIREBASE_API_KEY
        value: your_key_here
